#include "lang_zh.h"
// M5StickC的官方库只支持GB2312编码，所以只能另外安排这个GB2312编码的文件存储要用到的中文字符串
char *str_now = (char*)"当前", 
     *str_noClassLeft = (char*)"无剩余课程",
     *str_nextEvent = (char*)"下一个事件:", 
     *str_type = (char*)"类型:", 
     *str_classOver = (char*)"课程结束",
     *str_classReady=(char*)"课程预备",
     *str_classBegin=(char*)"课程开始",
     *str_lateForSchool=(char*)"学校迟到",
     *str_xieZuRequire=(char*)"斜足要求",
     *str_battery=(char*)"电池",
     *str_temperature=(char*)"温度",
     *str_chinese=(char*)"语文",
     *str_math=(char*)"数学", 
     *str_english=(char*)"英语", 
     *str_physics=(char*)"物理", 
     *str_chemistery=(char*)"化学", 
     *str_biology=(char*)"生物", 
     *str_PE=(char*)"体育", 
     *str_selfStudy=(char*)"自习", 
     *str_unknown=(char*)"未知",
     *str_nextClass=(char*)"下一节课";
